apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: swiggy-app
        image: 975050278083.dkr.ecr.ap-south-1.amazonaws.com/test:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
